# === TOKENIZER ===
t5_tokenizer: /workspace/Wan2.2/models/umt5-xxl-tokenizer
t5_encoder: google/umt5-xxl  # Encoder wird ggf. automatisch geladen – kannst du auch lokal machen

# === VAE ===
vae_path: /workspace/Wan2.2/models/sd-vae-ft-mse

# === UNet / Diffusion ===
unet_path: /workspace/Wan2.2/models/wan-ti2v-5b.safetensors

# === Output ===
output_dir: ./outputs
save_frames: True

# === Video Settings ===
resolution: 1280x704
frame_num: 16
sample_shift: 8
sample_guide_scale: 6

# === Optimierung ===
offload_model: True
t5_cpu: True
