python generate.py \
  --task ti2v-5B \
  --prompt "a glowing phoenix flying over a neon ocean at night" \
  --size 1024*640 \
  --frame_num 4 \
  --sample_steps 25 \
  --sample_shift 8 \
  --sample_guide_scale 6 \
  --ckpt_dir /workspace/Wan2.2/models \
  --save_file output/test_debug.mp4 \
  --offload_model True
