name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1) Platz auf dem Runner freiräumen (sonst "No space left on device")
      - name: Free disk space on runner
        run: |
          sudo rm -rf /usr/share/dotnet \
                      /opt/ghc \
                      /usr/local/lib/android || true
          docker system prune -af || true
          df -h

      # 2) Buildx aktivieren (BuildKit)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3) Login zu GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4) Build & Push (mit Cache). Kein load/pull, nur push.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/runpod-test-image:latest
          # Cache beschleunigt Folge-Builds & spart Platz
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Falls du deterministisch bauen willst, lass no-cache: true drin
          # no-cache: true





